# Generated by Django 5.0.7 on 2024-08-02 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
