# Generated by Django 5.0.7 on 2024-08-03 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0005_alter_booking_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='user',
            new_name='author',
        ),
    ]
