# Generated by Django 5.0.7 on 2024-08-11 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0006_rename_user_booking_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='author',
            new_name='user',
        ),
    ]
