# Generated by Django 5.0.7 on 2024-09-09 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0009_tourgroupdetail_tourthemes_tourtype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='author',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='car',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='duration',
        ),
        migrations.AddField(
            model_name='booking',
            name='car',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='tour.car'),
        ),
        migrations.AddField(
            model_name='booking',
            name='duration',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='booking',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='phone_number',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='booking',
            name='second_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tour',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='tour.tour'),
        ),
    ]
