# Generated by Django 5.0.7 on 2024-09-20 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0010_remove_booking_author_remove_tour_car_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='image',
        ),
        migrations.AlterField(
            model_name='tour',
            name='group_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.tourgroupdetail'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='themes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.tourthemes'),
        ),
        migrations.AlterField(
            model_name='tour',
            name='tour_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.tourtype'),
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='img')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.car')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='img')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tour.tour')),
            ],
        ),
    ]
